### ISSUE TITLE
Errores

### ISSUE THREAD

**Issue by Luisdwec** [Luisdwec/practica_dwec_gestor_presupuesto#1]
Buenas @pedroprieto tengo dos errores que no consigo subsanar en el test, he mirado los apuntes del año pasado, cosa que no quiero volver ha hacer y no doy con los errores.
Por otro lado he intentado en estas lineas https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/a64ffd8a26ae923e43219a223e672df3b32c999c/js/gestionPresupuesto.js#L8
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/a64ffd8a26ae923e43219a223e672df3b32c999c/js/gestionPresupuesto.js#L29
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/a64ffd8a26ae923e43219a223e672df3b32c999c/js/gestionPresupuesto.js#L41
Intentar crear otro codigo con algun if isNaN para comprobar que es un numro y positivo y no he coneguido nada.
Volvere a leer lo de infojava a ver si conigo algo si no ya me comenta todo lo que se oued mejorar en el codigo.
Saludos y gracias Pedro.

**Comment by LuisDaw** [comment]
No me lo puedo creer, por estas cosas perdi la ilusion el año pasado ya entre esto y el curro jajajajajaja
Estare más atento e intentare ceñirme a lo que pone.
Probare algun isNan o typeOf a ver si asi voy practicando mas y esta noche lo subo. Gracias @pedroprieto

**Comment by pedroprieto** [comment]
👍
