### ISSUE TITLE
Ponerme al dia

### ISSUE THREAD

**Issue by Luisdwec** [Luisdwec/practica_dwec_gestor_presupuesto#3]
BUenas @pedroprieto he vuelto de viaje por trabajo y quiere ver si retomo por donde me quede pero no se como pasar los datos del periodo para poder agrupar, es que no se me ocurre nada.
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/17241ff54d845b8e3ad59444a76f5c95e18bcfad/js/gestionPresupuesto.js#L145
no se si ponerlo un if pero no se como comprobar si viene dado en dias/meses/años o como viene.
Si me puedese dar una idea de como afrontarlo te lo agradeceria.
Saludos

**Comment by pedroprieto** [comment]
Buenas,

Tienes que utilizar la función `reduce`. En la tutoría de hoy lo comento.

Un saludo!!
