### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by Luisdwec** [Luisdwec/practica_dwec_gestor_presupuesto#4]
Buenas @pedroprieto tengo muchas dudas sobre com oafrontar esta practica.
He escrito algunas lineas de codigo pero no se como saber si lo basico que es mostrar el presdupuesto cambiado lo hace o no.
Tambien en los test me aparece en todos este error Unexpected token '('
no se si es por lo que comentaste de hacerlos en el navegador, volvere a ver la tutoria.
Pero si puedes revisar lo que tengo hecho hasta ahora y ver com ovoy te lo agradeceria.
Saludos.

**Comment by pedroprieto** [comment]
Buenas Luis,

Tienes un error de sintaxis aquí:
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/08a438734a973bfaf49ea61f23f472259d740654/js/gestionPresupuestoWeb.js#L10

Lógicamente, el código correcto sería:
```js
datosId.innerHTML = valor; 
```

Cuando te dé un error el test, inspecciona la línea que te indica.

Un saludo!!

**Comment by Luisdwec** [comment]
Buenas @pedroprieto creo que le qute los parantesis pero sige sin mostrarse nada y pruebo a poner tambien el presupuesto y no me aparece en el html:
<pre>
gestPresWeb.mostrarDatoEnId("presupuesto", gestPresupuesto.mostrarPresupuesto());
document.presupesto = gestPresupuesto.actualizarPresupuesto();
</pre>
No se si me falta algo mas pero no consigo realizar algo de la practica.
Gracias

**Comment by pedroprieto** [comment]
Buenas. Esto te sobra:
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/08a438734a973bfaf49ea61f23f472259d740654/js/gestionPresupuestoWeb.js#L11

Las líneas anteriores ya se encargan de realizar la tarea pedida.

Un saludo!

**Comment by Luisdwec** [comment]
Bueno pues nada sigo igual, no me aparece nada, leo los errores que me da el test y no lo entioendo creo que no entiendo nada
Gracias de todas maneras @pedroprieto

**Comment by pedroprieto** [comment]
Buenas,

- Esto te sobra:
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/1cc1f8c865d6f1d599f0564b1c5e8ef896bd673e/interaccionHTML.html#L58-L63
- Te sobran los paréntesis:
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/1cc1f8c865d6f1d599f0564b1c5e8ef896bd673e/js/gestionPresupuestoWeb.js#L2
- Aquí no debes importar la librería (no lo pide el enunciado):
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/1cc1f8c865d6f1d599f0564b1c5e8ef896bd673e/js/gestionPresupuestoWeb.js#L2
- Esto te sobra (no sé por qué lo pones):
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/1cc1f8c865d6f1d599f0564b1c5e8ef896bd673e/js/generarDatosEstaticos.js#L12
- A partir de aquí, puedes continuar con lo que pide el enunciado:
  ![imagen](https://user-images.githubusercontent.com/7632447/200266591-c0a6f677-f90a-4ce7-aba2-42a87193daab.png)
- Puedes ejecutar los tests para que se muestren en el navegador mediante `npx cypress open`. De esta manera tendrás más información sobre los errores y podrás ver lo que se carga en pantalla.

Ánimo y un saludo!!

**Comment by Luisdwec** [comment]
Buenas @pedroprieto a ver te cuento por puntos.
Se que lo primero me sobra ya q es un codigo que puse para saber si entendia algo, recuerda de de javascript solo se lo que estamos dando y de programacion lo que di hace ya unos cuantos años que aprobe el modulo de primero y al no trabajar en esto, solo practico cuando el trabajo me deja un rato.
Lo de los parentesis lo corrigo en las demas importaciones y en esta que me has marcado borro la linea, pense que al utilizar el actualizar presupuesto deberia de importarla, fallo mio.
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/1cc1f8c865d6f1d599f0564b1c5e8ef896bd673e/js/generarDatosEstaticos.js#L12 
esto lo puse para mostrar el presupuesto, al ponerme ese comentario, señal que no lo entendi bien.
Y a partir de ahi pues seguire dando palos de ciego a ver si consigo hacer la practica y si no pues lo dejare para otro año porque veo que no avanzo y cada vez entiendo menos,
Gracias por todo Pedro  un saludo.

**Comment by Luisdwec** [comment]
Puedes ejecutar los tests para que se muestren en el navegador mediante npx cypress open. De esta manera tendrás más información sobre los errores y podrás ver lo que se carga en pantalla.

Esto tengo que ejecutarlo en la consola del navegador?
Perdona de verdad pero es que no logro enterarme

**Comment by pedroprieto** [comment]
No: lo tienes que ejecutar en el terminal del sistema operativo. Es como `npm run test4`, pero en su lugar ejecuta `npx cypress open`.

Un saludo!
