### ISSUE TITLE
Errores

### ISSUE THREAD

**Issue by Luisdwec** [Luisdwec/practica_dwec_gestor_presupuesto#6]
Buenas @pedroprieto estoy realizando los primeros pasos y tengo dos errores.
1- No logro ver porque me muestra dos veces las etiquetas, como si las añadiera dos veces, he modificado esta linea un par de veces pero solo consigo o errores totales o que no me muestre las etiquetas
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/ade7ea1b240719c0fe3444d66e3f9e2bbbfc40e8/js/gestionPresupuestoWeb.js#L39
2- Tambien no consigo hacer que se muestre la fecha en formato ToIsoString, no se si desde esta linea se puede hacer o habria que crear alguna variable o funcion que transformara la fecha.
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/ade7ea1b240719c0fe3444d66e3f9e2bbbfc40e8/js/gestionPresupuestoWeb.js#L27
He intentado varias cosas pero no he obtenido resultado.
Gracias Pedro

**Comment by Luisdwec** [comment]
Buenas @pedroprieto ahora me aparece undefined.
Seguire dandole vueltas a ver si lo consigo.
Gracias

**Comment by Luisdwec** [comment]
Buenas @pedroprieto no he conseguido que el format ofecha me lo muestre bien, me ha salido varios mensajes de error y al final solo he conseguido que me muestre la fecha entera, al probar con toLocaleDateString me salia error que no era una funcion en los test.
Y la funcion agruopar gastos tampoco he sabido como mostrarla y no se si el bucle para que muiestre el valor y el gasto lo tengo bien ya que tambien me aparece error al mostrar la etiqueta H1.
A ver si le puedees dar un vistazo a ver que es lo que no he entendido para ver si lo consigo.
Gracias Pedro.

**Comment by pedroprieto** [comment]
Buenas,

- Aquí:
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/a5ce47f3349c39136309a4e4ea851ad0eb448fd3/js/gestionPresupuestoWeb.js#L27
  puedes utilizar lo siguiente:
  ```js
   let f = new Date(gasto.fecha);
   divFecha.innerText = f.toLocaleDateString(); 
  ```
- En cuanto a la de agrupación, te falta hacer la parte del fichero de datos estáticos para poder ver algo: https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/master/enunciados/interaccionHTML.org#fichero-jsgenerardatosestaticosjs (las 3 últimas líneas).
- En la función de agrupación, no es necesario que iteres aquí:
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/a5ce47f3349c39136309a4e4ea851ad0eb448fd3/js/gestionPresupuestoWeb.js#L65
  Una vez dentro del `map`:
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/a5ce47f3349c39136309a4e4ea851ad0eb448fd3/js/gestionPresupuestoWeb.js#L61-L62
  El parámetro `gasto` (yo no utilizaría ese nombre) es un array cuya posición `0` es la clave y la posición `1` el valor. Así, tendrías que crear dos `span` dentro del `map`: en el primero muestras `gasto[0]` y en el segundo `gasto[1]`.
- Por último, te falta añadir `divAgrupar` al elemento `IdElemento` para que se muestre en la página:
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/a5ce47f3349c39136309a4e4ea851ad0eb448fd3/js/gestionPresupuestoWeb.js#L55

Un saludo!

**Comment by Luisdwec** [comment]
Buenas @pedroprieto 
Ya voy consiguiendo algo, pero los datos que me muestra en agrupar no son correctos.
Ademas creo que me pasa como en el otro con las etiquetsas, me los muestra todos arriba y despues en cada div, pero como te digo no lomuestra bien.

**Comment by pedroprieto** [comment]
Buenas,

Esto no tiene sentido:
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/f8ecde545b4c393ebcc34ea203679f63db8aeefe/js/gestionPresupuestoWeb.js#L73

Tienes que añadir a `divAgrpGasto` los `span`. Y después, añadir a `divAgrupar` `divAgrpGasto`:

Un saludo!!

**Comment by Luisdwec** [comment]
Buenas @pedroprieto por aqui miramos a ver?
No consigo sacar el div agrupacion arriba, me lo repite en cada valor de periodo.
Luego la agrupacion me la hace en la misma linea sin separacion y sin nada.
Y cada vez que cambio algo me da errores como que el div agrupacion no esta declarado, etc. no se la verdad.
Vuelvo a subir los cambios de clase de span y lo vemos.
Gracias
