### ISSUE TITLE
mal funcionamiento

### ISSUE THREAD

**Issue by Luisdwec** [Luisdwec/practica_dwec_gestor_presupuesto#8]
Buenas @pedroprieto, trasteando la App veo que cuando modifico algo aparece bien pero los agrupados no cambian, es decir si pongo un gasto mayor no me aparece, si elimino todos los gastos sigue filtrando y no aparecen los nuevos y demas.
Eso habra que poner algo en repintar para que vuelva a pintar todos los filtrados de nuevo o hay que modificar los filtros de los agrupados?
Gracias Pedro

**Comment by pedroprieto** [comment]
Es correcto. `repintar` tendría que hacer esas operaciones también. Pero ya lo harás en la práctica de expresiones regulares.

Un saludo!

**Comment by pedroprieto** [comment]
Buenas,

No sé a qué te refieres... ¿Puedes concretarlo?

**Comment by Luisdwec** [comment]
Nada déjalo al estar fuera no tengo acceso a mi pc y no subí lo ultimo
Ya me apaño gravy
