### ISSUE TITLE
Boton cancelar

### ISSUE THREAD

**Issue by Luisdwec** [Luisdwec/practica_dwec_gestor_presupuesto#9]
Buenas @pedroprieto, he realizado otra vez la practica de formulario desde cero y sigo teniendo fallos y no consigo verlos, ya creo que estoy demasiado bloqueado.
En el boton de cancelar de cada gasto cuando le doy a editar, si consigo que me lo cierre el formualrio, pero en el de añadir gasto no  lo consigo.
En los test me da error en la linea 241, pero no consigo verlo.
En principio parece que funciona bien pero no pasa los test
Un fallo es este reading 'addEventListener que es de dicha linea y el otro es de de disable que tampoco logro entenderlo mucho ya que en boton añadir gasto formulario si lo deshabilita.
La verdfad es que llevo desde3 el viernes y sigo igual o peor la verdad.
Si le puedes dar un vistazo a ver que le pasa te lo agradeceria.
Saludos

**Comment by pedroprieto** [comment]
Buenas,
- Aquí no tienes referencia a `botonCancelar` (error del test y problema al cerrar):
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/2cea6a2b8d1defa91a8efc51b5f16b2cba260cc7/js/gestionPresupuestoWeb.js#L328
  Si acaso, estaría disponible en `event.currentTarget`

Un saludo!

**Comment by Luisdwec** [comment]
Vale pero me he quedado igual, la verdad.

**Comment by Luisdwec** [comment]
Hola Pedro, a ver que al final no hemos podido hablar esto bien, me ha pasado con esta resopuesta lo mismo que con el dateparse, que por mas vueltas que le he dado no ha salido.
Esta semana estoy mas libre por los examenes y no saldre de viaje, se que estaras liado pero si quieres podemos quedar y hacer lo que has comentado de la tutoria o bien ponline o presencial y vemos estos temas y me pongo al dia con las practicas.
No se si levantaras la mano en la correccion del examen ya que viendo las correcciones me han fallado unas pequeñas cosas pero buena ya vere si becesito recuperar este trimestre.
Ya me dices cuando podemos quedar que te venga bien y vemos el fallo de esta practicas de formularios.
Un saludo Pedro

**Comment by pedroprieto** [comment]
Buenas,

Esta semana es de exámenes, así que lo tengo complicado. En principio lo vemos el lunes en la tutoría.

Con respecto a tu error:
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/2cea6a2b8d1defa91a8efc51b5f16b2cba260cc7/js/gestionPresupuestoWeb.js#L325-L332

En esa función, `plantillaFormulario` no está definida: no es una variable accesible. Si lo que quieres es acceder al formulario, puedes hacerlo: `event` es un evento que se produce sobre el botón `cancelar`, por lo que `event.currentTarget` hará referencia a dicho botón. Así, la línea errónea quedaría:
```js
var botonCancelar = event.currentTarget; 
```

Y ahora ya podrías deshabilitarlo.

Espero habértelo aclarado. Un saludo!!

**Comment by Luisdwec** [comment]
Ok , lo pruebo esta noche y te digo para ver si asi puedo ir siguiendo las practicas.
La semana que viene si no salgo de viaje me acercare y si salgo pues ya quedaremos en otra ocasion.
Gracias

**Comment by Luisdwec** [comment]
Mas que dudas Pedro son los errores que me da que no se como arreglarlos, si que cambie la linea esa, pero no lo subi ayer, y sigue igual, el de editar formulario lo cierra, pero no consigo deshabilitarlo:
'<button.gasto-editar-formulario>' to have attribute 'disabled'
y el de añadir gasto es el que no hace nada.
Referente a la disponibilidad, cualquier tarde menos hoy que tengo el de Entorno Servidor, incluso el viernes por la mañana igual me lo dan libre y tambien podria conectarme.
Si esta tarde te veo lo comentamos a ver.
Gracias pedro por hecharme una mano.

**Comment by Luisdwec** [comment]
ah y me sigue tambien el error del addeventListener de la 241
t HTMLButtonElement.nuevoGastoWebFormulario (http://localhost:61208/js/gestionPresupuestoWeb.js:241:24)
Cancelar añadir gastofailed
Cannot read properties of null (reading 'addEventListener')

**Comment by pedroprieto** [comment]
Buenas,

Bueno, pues sube los cambios y dime el fallo que te da.

**Comment by Luisdwec** [comment]
Ya estan subidos, voy por partes
Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
este es el error de la linea 241 que me salta al pinchar en el boton añadir formulario de arriba y donde el boton cerrar no funciona
Al trastear me he dado cuanta que el split tampoco lo hace correctamente
Uncaught TypeError: Cannot read properties of null (reading 'split')
    at EditarHandle.handleEvent (gestionPresupuestoWeb.js:193:78)
EditarHandle.handleEvent @ gestionPresupuestoWeb.js:193
Y en el boton editar gasto el atributo disable tampoco lo pilla y el boton no se queda deshabilitado
he probado en el manejador submit con esto 
            event.currentTarget.disabled = true;
y nada no lo deshabilita.
Y creo que esos son basicamente los errores que me aparecen

**Comment by pedroprieto** [comment]
Buenas,

- Estas líneas te sobran (las tienes duplicadas más adelante):
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/57250b8320d01b6616cb1d649a4f60facd1ae184/js/gestionPresupuestoWeb.js#L232-L233
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/57250b8320d01b6616cb1d649a4f60facd1ae184/js/gestionPresupuestoWeb.js#L230
- Y aquí, lo que tienes que añadir es la plantilla, no el formulario (tendrías que poner `plantillaFormulario`):
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/57250b8320d01b6616cb1d649a4f60facd1ae184/js/gestionPresupuestoWeb.js#L245
- Luego, aquí añades un manejador de evento como si fuera una función (que está bien):
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/57250b8320d01b6616cb1d649a4f60facd1ae184/js/gestionPresupuestoWeb.js#L241
  pero en ese caso debes poner una función manejadora simple, sin el `this.handleEvent` (que sería para un objeto manejador de eventos):
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/57250b8320d01b6616cb1d649a4f60facd1ae184/js/gestionPresupuestoWeb.js#L326-L327

Un saludo!

**Comment by Luisdwec** [comment]
Ok, ya va mejorando, me sigue faltando el deshabilitar el boton cuando editamos el gasto por el formulario y ahora me sale un error de los gastos totales, pero lo dejo que si no no repaso el examen de esta tarde, a ver si esta noche los saco y si no mañana hablamos a ver
Gracias de nuevo por todo pedro

**Comment by Luisdwec** [comment]
Buenas @pedroprieto ya se donde esta el fallo, pero por mas que veo el codigo y pruebo no doy con el fallo.
Es en la parte de editar formulario, a traves del form, no de los prompts, que falla las etiquetas, el split no separa y no reinicia las etiquetas, si no que las suma de nuevo aunque las borre, el valor que no lo coge, lo cambio pero al enviar no lo cambio, de hay el fallo en el test ya que modificas el del seguro pero no lo coge, y el boton que no consigo dar con el, ni mediante el evnt.currentTarget ni a traves del elementById para deshabilitarlo.
En el boton de editar por los prompt, tampoco recorta ni borra las etiquetas.
Voy a subir los cambios y las modificaciones que he hecho que por lo menos ya pasan 3 ;-)

**Comment by pedroprieto** [comment]
Buenas,

- El botón está disponible en `event.currentTarget`:
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/8527fdd324c462ba38937e61b08afbb897818d55/js/gestionPresupuestoWeb.js#L297-L298
  Quedaría:
  ```js
  let botonEditarFormulario = event.currentTarget;
  botonEditarFormulario.disabled = true; 
  ```
- Para volver a habilitar el botón al pulsar en `Cancelar`, debes localizar dicho botón dentro de la función:
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/8527fdd324c462ba38937e61b08afbb897818d55/js/gestionPresupuestoWeb.js#L315
  Igual que localizas el formulario aquí:
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/8527fdd324c462ba38937e61b08afbb897818d55/js/gestionPresupuestoWeb.js#L316
  Puedes buscar el botón de varias maneras: a través de `previousSibling` del formulario (hermano anterior):
  ![imagen](https://user-images.githubusercontent.com/7632447/204771342-249ab687-1144-47f0-b38f-45480413e8f6.png)
  `event.currentTarget.parentNode.previousSibling` te devolverá el botón que buscas.
- Otra opción es pasar una referencia al botón de Editar al objeto `cancelarFormulario`:
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/8527fdd324c462ba38937e61b08afbb897818d55/js/gestionPresupuestoWeb.js#L307-L308
  ```js
  let cancelarFormulario = new manejadorBotonCancelarFormulario(); 
  cancelarFormulario.botonEditar = event.currentTarget; // Pasas una referencia al botón de editar
  cancelarFormulario.className = "button.cancelar" 
  ```
  Así, en el manejador tendrás acceso a él y podrás habilitarlo:
  https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/8527fdd324c462ba38937e61b08afbb897818d55/js/gestionPresupuestoWeb.js#L314-L318
  ```js
  function manejadorBotonCancelarFormulario() { 
     this.handleEvent = function(event) { 
         event.currentTarget.parentNode.remove(); 
         this.botonEditar.disabled = false;
     } 
  } 
  ```
- En cuanto a las etiquetas, dos cosas:
  - La función `anyadirEtiquetas` admite una lista de parámetros, no un array:
    https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/8527fdd324c462ba38937e61b08afbb897818d55/js/gestionPresupuestoWeb.js#L343
    Por lo que debes hacer la transformación:
    ```js
    this.gasto.anyadirEtiquetas(...sepEtiquetas);
    ```
  - Y por último, previamente debes resetear `this.gasto.etiquetas`, o se te duplicarán. Por ejemplo: `this.gasto.etiquetas = [];`

Un saludo!

**Comment by Luisdwec** [comment]
Buenas @pedroprieto vale visto los fallos y muchas gracias por las respuestas volvere a repasarme lo del event.currentTarget porque no lo veo muy claro lo de hacer referencia.
No se porque me falla lo de actualiazr gastos, ya que si en el formulario coge todo bien y los actualiza, no entiendo porque no actualiza el valor, tendra algo que ver el formato en el que lo pase desde el formualrio?
Seguire mirando a ver donde esta el fallo y si no lo encuentro ya te lo dire esta noche.
Por todo lo demas ya esta subido y arreglado
De nuevo gracias por todo Pedro.

**Comment by Luisdwec** [comment]
Buenas otra vez @pedroprieto , le he dado mil vueltas al codigo y no veo donde esta el error.
He modificado la funcion de actualizarValor pero como es normal no he consigo nada, ya que solo falla en el formulario de editar.
Buscando ver algo, he puesto en el css un padding para que no se viera tan junto los filtrados por dias, mes, año
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/981555cddb0d61d08ddc29859cc5b4e473f24600/css/estilos.css#L11
le he creado una funcion al filtrado de gastos para que se actualice al repintar, funciona pero no se si estara bien hecha, se lo dejo aqui por si quiere verla.
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/981555cddb0d61d08ddc29859cc5b4e473f24600/js/generarDatosEstaticos.js#L43
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/981555cddb0d61d08ddc29859cc5b4e473f24600/js/gestionPresupuestoWeb.js#L153
Pero vamos que lo que me sigue fallando de los gastos no logro ver donde esta el fallo.
Me da error en la linea 104 del test6 del gasto de la linea 24 creo pero que eso es la unica informacion que me da.
Si lo puedes ver te lo agradeceria, ya no se que mas mirar la verdad, lo siento mucho darte tanto follon.
Gracias de nuevo Pedro

**Comment by Luisdwec** [comment]
BUenas @pedroprieto , ok vale es cierto, que negado, perdona.
Ya lo he cambiado, no se si sera lo correcto o podia ahorra codigo pero la he hecho asi,
https://github.com/Luisdwec/practica_dwec_gestor_presupuesto/blob/297aaf08c5857ca521a1168aa8cecd9dc4ccbcde/js/gestionPresupuestoWeb.js#L254
Un saludo Pedro y gracias
